[build]
  functions = "functions/"
[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "/api/*"
  to = "http://api.exchangeratesapi.io/v1/:splat"
  status = 200
  force = true